# Generated by Django 5.0.6 on 2026-05-07 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(choices=[('Barcelona', 'Barcelona'), ('Madrid', 'Madrid'), ('Valencia', 'Valencia'), ('Sevilla', 'Sevilla'), ('Zaragoza', 'Zaragoza'), ('Málaga', 'Málaga'), ('Murcia', 'Murcia'), ('Palma', 'Palma'), ('Bilbao', 'Bilbao'), ('Granada', 'Granada')], max_length=50)),
                ('role', models.CharField(choices=[('client', 'Client'), ('seller', 'Seller')], default='client', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TokenJWT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_reviews', to='api.user')),
                ('store', models.ForeignKey(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.user')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Dairy', 'Dairy'), ('Bakery', 'Bakery')], max_length=20)),
                ('city', models.CharField(choices=[('Barcelona', 'Barcelona'), ('Madrid', 'Madrid'), ('Valencia', 'Valencia'), ('Sevilla', 'Sevilla'), ('Zaragoza', 'Zaragoza'), ('Málaga', 'Málaga'), ('Murcia', 'Murcia'), ('Palma', 'Palma'), ('Bilbao', 'Bilbao'), ('Granada', 'Granada')], max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
