# Generated by Django 5.0.6 on 2026-05-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('L', 'L'), ('ud', 'ud'), ('docena', 'docena'), ('manojo', 'manojo'), ('bandeja', 'bandeja')], default='kg', max_length=10),
        ),
    ]
