# Generated by Django 5.0.6 on 2026-05-10 17:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('descripcio', models.TextField(blank=True)),
                ('imatge', models.URLField(blank=True)),
                ('preu', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('unitat', models.CharField(choices=[('kg', 'Kg'), ('g', 'G'), ('L', 'Litre'), ('ud', 'Unitat'), ('docena', 'Docena')], default='kg', max_length=10)),
                ('ciutat', models.CharField(choices=[('Barcelona', 'Barcelona'), ('Madrid', 'Madrid'), ('Valencia', 'Valencia'), ('Sevilla', 'Sevilla'), ('Zaragoza', 'Zaragoza'), ('Malaga', 'Malaga'), ('Murcia', 'Murcia'), ('Palma', 'Palma'), ('Bilbao', 'Bilbao'), ('Granada', 'Granada')], max_length=20)),
                ('adreca', models.CharField(max_length=255)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoriaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('correu', models.EmailField(max_length=100, unique=True)),
                ('contrasenya', models.CharField(max_length=255)),
                ('telefon', models.IntegerField(validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(999999999)])),
                ('ciutat', models.CharField(choices=[('Barcelona', 'Barcelona'), ('Madrid', 'Madrid'), ('Valencia', 'Valencia'), ('Sevilla', 'Sevilla'), ('Zaragoza', 'Zaragoza'), ('Malaga', 'Malaga'), ('Murcia', 'Murcia'), ('Palma', 'Palma'), ('Bilbao', 'Bilbao'), ('Granada', 'Granada')], default='Barcelona', max_length=20)),
                ('rol', models.CharField(choices=[('Vendedor', 'Vendedor'), ('Comprador', 'Comprador')], default='Comprador', max_length=10)),
                ('favorits', models.ManyToManyField(blank=True, related_name='favorit_de', to='app.producte')),
            ],
        ),
        migrations.CreateModel(
            name='TokenJWT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuari')),
            ],
        ),
        migrations.CreateModel(
            name='Ressenya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrelles', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentari', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('autorFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressenyes_escrites', to='app.usuari')),
                ('botigaFK', models.ForeignKey(limit_choices_to={'rol': 'Vendedor'}, on_delete=django.db.models.deletion.CASCADE, related_name='ressenyes', to='app.usuari')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.AddField(
            model_name='producte',
            name='vendedorFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productes', to='app.usuari'),
        ),
    ]
